 create table address (
        id_address bigint generated by default as identity,
        city varchar(255),
        country varchar(255),
        postal_code varchar(255) not null,
        state varchar(255),
        street varchar(255),
        primary key (id_address)
    );
create table customer (
        birth_date date,
        id_address bigint unique,
        id_customer bigint generated by default as identity,
        first_name varchar(100) not null,
        last_name varchar(150) not null,
        email varchar(255),
        gender varchar(255),
        phone_number varchar(255),
        primary key (id_customer)
    );
alter table if exists customer 
       add constraint address_customer 
       foreign key (id_address) 
       references address;

INSERT INTO address (city, country, postal_code, state, street) 
VALUES 
('São Paulo', 'Brasil', '01000-000', 'SP', 'Rua da Consolação, 123'),
('Rio de Janeiro', 'Brasil', '20000-000', 'RJ', 'Avenida Atlântica, 456'),
('Belo Horizonte', 'Brasil', '30100-000', 'MG', 'Rua São Paulo, 789'),
('Porto Alegre', 'Brasil', '90000-000', 'RS', 'Rua dos Andradas, 101'),
('Curitiba', 'Brasil', '80000-000', 'PR', 'Rua XV de Novembro, 202');

INSERT INTO customer (first_name, last_name, email, gender, phone_number, birth_date, id_address) 
VALUES 
('Carlos', 'Silva', 'carlos.silva@example.com', 'Masculino', '21987654321', '1985-06-15', 1),
('Fernanda', 'Oliveira', 'fernanda.oliveira@example.com', 'Feminino', '21923456789', '1990-11-23', 2),
('Mariana', 'Souza', 'mariana.souza@example.com', 'Feminino', '31987654321', '1982-04-10', 3),
('Roberto', 'Pereira', 'roberto.pereira@example.com', 'Masculino', '51923456789', '1975-08-30', 4),
('Patrícia', 'Costa', 'patricia.costa@example.com', 'Feminino', '41987654321', '1995-12-05', 5);
